[oobe]
command = /usr/lib/wsl/wsl-setup
defaultUid = 1000
defaultName = Algorek-2.0

[wsl2]
systemd=true

[shortcut]
icon = /usr/share/wsl/algorek.ico

[windowsterminal]
ProfileTemplate = /usr/share/wsl/terminal-profile.json
